version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gym-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: soto
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gym-pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata:
